[package]
name = "hostel"
version = "0.1.0"
edition = "2024"

[dependencies]
goblin = {version = "0.10.4"}
iced-x86 = {version = "1.21.0", default-features = false, features = ["std", "decoder", "masm"]}
