[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.11.0"
spin = "0.10.0"
thiserror = { version = "2.0", default-features = false }
kernel-tests = { path = "../kernel-tests" }

[profile.release]
panic = "abort"
lto = true

[[bin]]
name = "kernel"
test = false
